package com.example.iffah.ui.theme

import androidx.compose.ui.graphics.Color

// === ألوان الثيم الداكن (اللي نستخدمها حالياً) ===
val DarkPrimary = Color(0xFF1DB954)
val DarkOnPrimary = Color(0xFF003914)
val DarkPrimaryContainer = Color(0xFF005322)
val DarkOnPrimaryContainer = Color(0xFFA8F5B8)
val DarkSecondary = Color(0xFFB8CCB8)
val DarkOnSecondary = Color(0xFF233424)
val DarkSecondaryContainer = Color(0xFF394B39)
val DarkOnSecondaryContainer = Color(0xFFD4E8D4)
val DarkTertiary = Color(0xFFA1CED0)
val DarkOnTertiary = Color(0xFF013738)
val DarkTertiaryContainer = Color(0xFF1F4E50)
val DarkOnTertiaryContainer = Color(0xFFBCEAED)
val DarkBackground = Color(0xFF0F0F1A)
val DarkOnBackground = Color(0xFFE1E3DE)
val DarkSurface = Color(0xFF1B1B2F)
val DarkOnSurface = Color(0xFFE1E3DE)
val DarkSurfaceVariant = Color(0xFF424940)
val DarkOnSurfaceVariant = Color(0xFFC1C9BD)
val DarkOutline = Color(0xFF8B9388)
val DarkOutlineVariant = Color(0xFF424940)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// === ألوان الثيم الفاتح ===
val LightPrimary = Color(0xFF006E2C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF8FF59C)
val LightOnPrimaryContainer = Color(0xFF002108)
val LightSecondary = Color(0xFF526352)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD4E8D4)
val LightOnSecondaryContainer = Color(0xFF101F10)
val LightTertiary = Color(0xFF386869)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBCEAED)
val LightOnTertiaryContainer = Color(0xFF002021)
val LightBackground = Color(0xFFFBFDF7)
val LightOnBackground = Color(0xFF191D17)
val LightSurface = Color(0xFFFBFDF7)
val LightOnSurface = Color(0xFF191D17)
val LightSurfaceVariant = Color(0xFFDEE5D9)
val LightOnSurfaceVariant = Color(0xFF424940)
val LightOutline = Color(0xFF727970)
val LightOutlineVariant = Color(0xFFC1C9BD)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// === ألوان مخصصة ===
val PrimaryGreen = Color(0xFF4CAF50)
val SecondaryGreen = Color(0xFF388E3C)
val DangerRed = Color(0xFFF44336)
val LightGreenBg = Color(0xFFF1F8E9)
val WarningOrange = Color(0xFFFF9800)
